### ISSUE TITLE
potential for spell check?

### ISSUE THREAD

**Issue by Gladcraft** [thomaswilburn/Caret#328]
Hi, I'm using Caret quite a bit as an initial environment for writing.

Are there some easy ways to integrate spell checking into Caret?  

Thanks,
David

**Comment by thomaswilburn** [comment]
I'd do it if we could take advantage of the Chrome spellchecking, but I don't want to ship a language dictionary (or multiple language dictionaries) as a part of the Caret package, and as far as I'm aware there's no way to tap into the browser's built-in utility.

**Comment by Gladcraft** [comment]
Thanks for your response.  I'll paste into a gmail draft or something meanwhile.

**Comment by nortexoid** [comment]
Oh, this is a real shame! Why not ship one of the libreoffice or dictionaries form hunspell/aspell/etc.? Or give the option?

**Comment by thomaswilburn** [comment]
Package size is a concern for Caret, and I'm hoping to keep it under 2MB. Shipping a dictionary--plus the code required to do spell-checking, which is not built-in to Ace--would probably blow us past that limit.

**Comment by nortexoid** [comment]
The aspell English dictionary is only 171kb: ftp://ftp.gnu.org/gnu/aspell/dict/en. I don't know how much the code would be to enable on the fly spell check, but at least the dictionary's quite small. (I guess you would have to enable an option to download dictionaries as the user chooses the language.)

**Comment by thomaswilburn** [comment]
That's true. I have a bunch of questions about the format, but you're right: the dictionary is much smaller than I thought it was. But I was assuming that Caret would ship with the dictionary for any supported language (and it's officially translated into at least four or five at the moment). Right now it doesn't include any network permissions, which keeps my privacy statement nice and short.

So to keep this productive, here's my pitch: a spell check would be a *great* opportunity for a plugin, so that people who want it can have it, and people who don't pay no download or startup penalty. And it would be a great use case to find out where the API isn't capable enough to support plugin use--I'd be more than happy to take pull requests or bug reports on the plugin API.
