### ISSUE TITLE
Feature Request: Set Ctrl-D to act more like Sublime Text

### ISSUE THREAD

**Issue by pdebelak** [thomaswilburn/Caret#330]
In Sublime Text if you don't have a word selected `Ctrl-D` will select the word your cursor is currently in. If you have a selection, `Ctrl-D` then selects the next matching text using a multi-cursor.

Currently, if you do not have a selection Caret selects the word your cursor is in plus the next matching text. I prefer the Sublime Text functionality.

I can make a pull request with that change if it is something that other think would be worthwhile to add to Caret.

**Comment by thomaswilburn** [comment]
If it's doable, I'd be happy to take the pull request for this. I never use Ctrl-D without having a word selected, so I'd never noticed the difference.

If you need to add a binding to do this, rather than just using the built-in Ace command (which is what we're doing now, I think), add it in `aceBindings.js` with the other Sublime-like shims, please.
