### ISSUE TITLE
project sidebar request

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#340]
I would like an option to **disable** the project sidebar from opening AND still have a project.

The delay _seemed_ helpful, but recently the project sidebar is popping out more when the mouse pointer strays. Maybe it is simply that I am using Caret more and more and more. Caret is great... thank you.

I prefer to use `Tools > Go To...` to open files that I know are in the project.
Not only would the project sidebar **not get in the way**, but the `Tools > Go To...` is so much **faster**!
If I need access to files I do not remember in the project, I can use the Chromebook `File.app`.

**Comment by thomaswilburn** [comment]
That's... an interesting idea. I'll keep it in mind. Atom allows you to toggle viewing the sidebar, but theirs is much more intrusive than ours. That said, it shouldn't be hard to add a bindable command for toggling the display class on the sidebar.

On the other hand, since you're already using go-to, you could just get used to hitting Ctrl-P instead of touching the mouse and never worry about it, which is what I do 90% of the time.

**Comment by broomdodger** [comment]
Thank you for considering.
I use go-to via ctrl-p.
The go-to `fuzzy` ? search is great.
I usually open a file with 2-3 keystrokes!

Caret works very well with just keyboard navigation.

I do not on purpose mouse to the sidebar.
It may be the trackpad is very sensitive and my palm is activating it.
It is always a surprise, and annoyance, when the sidebar jumps out.

**Comment by grit96** [comment]
Would reusing the `autoHideProject` setting make sense?
```
{
  'autoHideProject': true, // autohide
  'autoHideProject': false, // show
  'autoHideProject': 'hidden' // hide
}
```

**Comment by thomaswilburn** [comment]
That's not a bad idea.
