### ISSUE TITLE
Cursor returns to top of file when editing over SSHFS

### ISSUE THREAD

**Issue by charukiewicz** [thomaswilburn/Caret#373]
Right off the bat I will say that this issue is very similar to #299 which was closed a couple of months ago.  I am using Caret inside of ChromeOS and I have a remote directory mounted using SSHFS (which is available via [Dev-Install](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/install-software-on-base-images)).

When you are editing files in a directory mounted via SSHFS this cursor bounce to the top of the file seems to happen *all the time*.  I understand the justification for having this behavior for editing local files but this makes Caret virtually unusable when used the way I am using it (which I think other people may do as well).  For the time being I have switched to regular ssh + tmux + vim, but I would love to continue to use Caret.  I suggest making this behavior a toggleable option with the default behavior being set to no bouncing.

**Comment by thomaswilburn** [comment]
This option exists! Enable `disableReload` in the user preferences to turn it off. This will cause Caret to ignore file modification times for the purpose of reloading the editing buffer, so make sure you're not trying to touch something while another legitimate process (like some sort of build) also edits the file, because you'll start overwriting each other.

**Comment by charukiewicz** [comment]
Oh woops.  I guess since this was added relatively recently it didn't reflect in my user.json file.  I should have checked the default configuration file.

Thanks for being one step ahead of me!
