### ISSUE TITLE
NW.js version?

### ISSUE THREAD

**Issue by geordieF** [thomaswilburn/Caret#383]
Hey, do you think it would be a good idea to port this to NW.js(node-webkit)?
I haven't got much time on my hands (I've got about 7 assignments due next week) so I don't want to waste time doing something nobody wants. Basically, it would function identically, but it would run natively. So, what do you think?

**Comment by thomaswilburn** [comment]
I don't have any objections. I think there's not as much call for it, what with Brackets and Atom both filling that nice, but I'd be curious if it's possible.

**Comment by thomaswilburn** [comment]
If you're thinking about doing this, incidentally, you should mostly just need to search the code for `chrome.` and see where we call the Google APIs. Mostly these are isolated in various wrappers, like the File module, but there are some places (like notifications) where they're not. 

It would also be interesting to see if this would work better with Electron Shell compared to NWjs, since it would probably map better to the background page model that Chrome Apps use.

**Comment by geordieF** [comment]
Not needed, as NW.js supports chrome app now.
