### ISSUE TITLE
Cursor jumps to beginning of document

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#413]
NB: Working from Samsung Chromebox on Stable (up-to-date)

The cursor often repositions itself at row 1, column 1. This is unintentional on my part and seems to happen most just after making a tab active. 

Workaround: Switch to document, position cursor with mouse, use arrow key on keyboard. This seems to stop the bug from happening

**Comment by thomaswilburn** [comment]
Chances are you're triggering Caret's auto-reload feature--it thinks the file has changed because the modification time is newer than it remembers, so it has reloaded the file and put the cursor at the top. Usually this happens because you're working on a remote file system.

We could probably remember where the cursor is, but then I'd get complains that the cursor was jumping around randomly, and it's frustrating enough as it is.

There's an option in the user preferences to disable automatic reloads, and you may want to turn that on if you're going to be working on filesystems that return unpredictable file mtime values. Otherwise, I believe this is working as intended.

**Comment by wesort** [comment]
Perfect! Thanks.
