### ISSUE TITLE
Unable to add two directories of same name

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#414]
Caret seems unable to load two different directories (from different projects) if they have the same name.

**Comment by thomaswilburn** [comment]
I don't see anything in the code to explain that, but I'll take a look.

**Comment by kresli** [comment]
works fine for me. Any additional info would be helpful

**Comment by wesort** [comment]
Could be to do with my set-up then:
- Chrome OS (stable builds)
- Directories loaded from remote file systems mounted from [SFTP Chrome App](https://chrome.google.com/webstore/detail/sftp-file-system/gbheifiifcfekkamhepkeogobihicgmn)
- Tested with directories stored locally (Downloads) too through with the following:
  - directory 1 name: "test-01" (top level, two unique files inside)
  - directory 2 name: "test-01" (stored inside another directory named "test-02", has a third unique file inside)

When trying to add the second directory from Caret (Project > Add Directory) nothing happens.

**Comment by thomaswilburn** [comment]
I can duplicate this on Windows, just with local directories. The problem is that the "fullPath" property of the directory entry is truncated by default when Chrome hands it to us. We can get the full display path of the file, but it'll require changing over to an async loop inside the project manager, and that's not something I can fix right away. I will add it to the backlog, though.

**Comment by wesort** [comment]
Fair enough and thanks.
