### ISSUE TITLE
Feature suggestion: option to notify on search wrapping

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#421]
It would be nice to have an option to notify the user (e.g., with a JavaScript alert) when a search wraps to the beginning again.

**Comment by thomaswilburn** [comment]
We actually can't call alert(), it's not allowed in Chrome apps. You may have been fooled by my beautifully crafted dialog boxes.

Anyway, this isn't really feasible because we don't know when the search wraps. It's an Ace widget, and although there's a long-standing bug to write a custom replacement, it's way on the back burner right now.

Also, I do kind of hate those dialogs. I'd be okay with a toast in the status bar, when the time comes.

**Comment by thdoan** [comment]
Yes, I toast would also do. Just something to alert the user when they are quickly doing a "find next".
