### ISSUE TITLE
Modified keyboard shortcut, but shortcut hint not changed in menu

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#422]
I changed:

```
"Ctrl-R": { "command": "palette:open", "argument": "reference" },
```

to:

```
"Ctrl-2": { "command": "palette:open", "argument": "reference" },
```

But the menu still shows "Go to Reference         Ctrl-R".

**Comment by thomaswilburn** [comment]
You need to unbind the old key, because user settings are combined with the defaults, and your version won't be the first key the menu system finds in the merged config object. Try adding `"Ctrl-R": null` to your keys.json, and then yours will be the only valid binding for that command.

I'm not sure this is great behavior, but it is consistent with the way that user.json works, and so we've retained it for now.
