### ISSUE TITLE
Feature suggestion: show save prompt when reverting modified file

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#425]
I hope to see an option to show a Save/Discard/Cancel dialog when you select File / Revert on a file that has been modified.

**Comment by thomaswilburn** [comment]
Does any other editor do this? I think it's usually understood that reverting a file will have destructive consequences to the current buffer contents.

Thinking about it, I'm not really sure what the benefit would be. By default, revert == discard. Offering to save is redundant, because now you're just loading the same text you just saved.

Cancel, I can maybe see. But we allow a lot of destructive operations without offering cancel, and I would need a good reason that this is different.

**Comment by thdoan** [comment]
Both desktop editors that I use on a daily basis have this:

Notepad++: File / Reload from Disk will prompt if modified buffer is unsaved
SciTE: if you set are.you.sure.on.reload = true

I guess I was just trying to emulate the desktop experience, but you do have a point -- I don't remember the last time I clicked on Save when I got a prompt on reverting in Notepad++ or SciTE.
