### ISSUE TITLE
Not-so-readable dialogs in dark theme

### ISSUE THREAD

**Issue by dar5hak** [thomaswilburn/Caret#427]
[**TL;DR:** Orange on white is hard to read.]

Currently, dialogs always use the `@accent` color for links and buttons on a white background. This is fine in the light UI theme, because it results in `#808` on white. However, with the dark theme, it ends up with`#FFA200` on white.

![image](https://cloud.githubusercontent.com/assets/8205055/9440692/a9cae4c8-4a8e-11e5-8aa7-b8378abfad72.png)

The problem is that the contrast ratio goes a bit too low, and the text becomes hard to read, especially for people with visual impairments. It even violates the WCAG for contrast ratio ([proof](https://leaverou.github.io/contrast-ratio/#%23FFA200-on-white)).

I have thought of two solutions for this:

1. Hardcode the link and button color to `#808` in `dialog.less`, or
2. Introduce new variables `@accent-light` and `@accent-dark` in the seed files, and assign each to `@accent`, depending on the theme. In `dialog.less`, use the `@accent-light` color.

I hope you'll agree that making dialogs follow the UI theme isn't a good idea. Please tell me what approach you prefer, and I can make a PR.

**Comment by thomaswilburn** [comment]
I don't know who the WCAG is, or why I'm supposed to care, but I take your point. That said, I don't think either of the solutions is particularly elegant. If you need to darken the accent in the case of the dialogs, which do break from the rest of the UI in terms of background, use a [conditional guard](http://lesscss.org/features/#css-guards-feature) to set the link color a little darker in `dialog.less`.

**Comment by dar5hak** [comment]
Got it. I'll reach home and hack this.in a couple hours.

(WCAG is basically W3's guidelines for accessibility.)

**Comment by dar5hak** [comment]
Hi @thomaswilburn, I read it up, and the only logic I could come up with, is that when the accent color is `#FFA200`, set the link/button color to `darken(@accent, 20%)` or something. But apparently, this is not elegant. What if someone changes `#FFA200` to something else?

What do you suggest?

**Comment by thomaswilburn** [comment]
LESS has a set of utility functions for extracting components of a given color, such as `lightness()`, and you could easily just check that the luminance is more or less than 50%. If you're really worried about the strict WCAG guidelines, you could compute the ratio between `@accent` and `@background`, and adjust the former accordingly if the ratio is unfavorable.

I don't particularly think you should worry about other people altering the colors in the UI layer. We don't expose that the way that people can customize the syntax themes. If someone's decided to change the LESS files, it's *caveat emptor* and they will need to figure out new colors for themselves.

If you are going to set a new color for the dialogs, rather than darkening the orange, I think it'd be best to just use a dark gray. I don't think changing the orange is going to harmonize well with the other highlights and colors onscreen.

**Comment by dar5hak** [comment]
> I don't think changing the orange is going to harmonize well with the other highlights and colors onscreen.

Exactly. I tried gray -- it's readable but looks rather bland. What I'm wondering is, what's wrong with violet? We're already using it, and it looks good too. Moreover, the dialogs break from the rest of the UI anyway.

**Comment by thomaswilburn** [comment]
I don't have a strong objection, but I didn't really want to add an 
additional color to each theme's palette if I didn't have to. The 
concept of foreground-background-accent for each theme is pretty strong. 
Grey (or a desaturated blue-ish gray, like the dark background) is 
simpler.

Thomas
