### ISSUE TITLE
Indentation preference is ignored

### ISSUE THREAD

**Issue by gzip** [thomaswilburn/Caret#441]
I'd like to use 4 spaces for tab instead of 2 so I opened `Settings > Preferences` and changed "indentation" to 4, then closed and reopened Caret (1.5.15). The setting didn't take effect.

**Comment by thomaswilburn** [comment]
Did you save the preferences file? You shouldn't need to restart Caret, it should reload the config file as soon as you save it. Your file does also need to be valid JSON (plus comments, which get stripped out).

**Comment by thomaswilburn** [comment]
I just tested this and couldn't repro--after changing, Caret immediately switched to 4-space indentation. It may be tough to figure out whether it has worked at first if you're in a 2-space indentation file (such as the preferences JSON), because it will only go 2 spaces to the next tab stop (after that, and on new lines, it'll go 4 spaces).

**Comment by gzip** [comment]
I did save the prefs file and only re-opened after that didn't take effect. It's definitely not working for me. I'm on a Chromebook if that matters.

**Comment by gzip** [comment]
After playing around with more settings it looks like none of them take effect. I reset preferences as a sanity check for valid json but no difference.

**Comment by thomaswilburn** [comment]
If nothing is taking effect, that's usually a sign that it wasn't able to parse your settings as JSON. I'm on a Chromebook too, that's definitely not the issue.

**Comment by gzip** [comment]
I had to close the preferences file and reopen it after resetting it. Now it works, so it must've been a parsing error. Thanks.

**Comment by gzip** [comment]
It was bugging me so I had to track down the problem. Not really invalid json, but it tripped up the parser somehow. This was the problem line:
`"ignoreFiles": "node_modules|\.*",`

**Comment by thomaswilburn** [comment]
Had that been moved to the last line, maybe? The trailing comma would be a problem for JSON if so.

**Comment by gzip** [comment]
The line wasn't moved and I verified the json by pasting it into chrome console and wrapping in parentheses - it parsed fine. It looks like the presence of `\.` in the string is the culprit for some reason. Even `\\.` is fine. It's also a valid regex either way. Anyway, my intention was more like `"node_modules|^\\..+"` which does work to hide dotfiles.

**Comment by thomaswilburn** [comment]
Weird. I'll look into that, it doesn't sound like something that should break it.

**Comment by thomaswilburn** [comment]
Huh, so it turns out that's not valid JSON. According to the spec, you're not allowed to escape arbitrary characters inside of JSON strings. 

Either way, since we're generating the blacklist regex by way of the string and `new RegExp`, it would need to be double-escaped anyway, so it's probably all for the best. I may add a note about this--thanks for finding that!

**Comment by gzip** [comment]
Ah, interesting. Never come across that before. Sure enough, this throws: `JSON.parse('{"foo":"\\."}');`.

It looks like the UI is usually pretty clear about invalid JSON (the red Xs on each line). Strange that this case slips through? That behavior would be better than a note if it could apply here as well.

Thanks again. I'm new to Chromebook and have tried several editors. Caret has been the best!
