### ISSUE TITLE
Add highlighting and linking to project search results

### ISSUE THREAD

**Issue by brismuth** [thomaswilburn/Caret#450]
We should be able to jump to files by clicking on results in tabs created by project-wide search the way you can in sublime. Also, the results page should be highlighted instead of being rendered as plaintext. I'm going to start working on implementing it this weekend.

**Comment by thomaswilburn** [comment]
So I was looking at how Zed does this, and I believe they're actually trapping all keys and events into their own handler in order to react to search interaction. They swap the search keyhandler in and out whenever the editor session changes. I'm not wild about that, for a lot of reasons, but mostly because I think that's the kind of thing that's easy to screw up. Also I kind of hate Ace's keyboard handler, which has not historically had a super-stable API, and I want to interact with it as little as possible.

Unfortunately, sessions (the basis of Caret's Tab class) don't handle input events at all, so we can't build on Ace functionality to handle events. It may be possible to add an optional callback to Tabs (such as an `onInputEvent`) that, if present, is called by the editor on any input. But we'd have to be able to hook into the event system, and right now I'm still not sure where to do that.

The other option, I think, would be to create markers using the session's `addMarker` function, and add event listeners to the DOM elements created there. That'll handle the mouse, but it wouldn't react on Enter, which would be a shame.

I'd love to hear a more elegant solution to this problem. Right now, I don't have any good suggestions. But I'm sure we can find something that doesn't feel like a total hack, or require tracking whether a search tab is focused on every keystroke.

**Comment by brismuth** [comment]
I was looking at options for click events in Ace and found [this Gist](https://gist.github.com/orbitbot/27f042995d03372fecaa). It's quite a bit of code to get the desired effect, but it seems to work really well and looks good. You can see it in action here. 
http://jsbin.com/jehopaja/30/edit?html,output

**Comment by thomaswilburn** [comment]
That looks similar to what I had in mind, but it's based around dynamic markers--you can type a new link into that document and it becomes a hyperlink. Since we don't plan on letting people edit or alter the search results (I was actually thinking we should make them read-only, but had forgotten to mention it), I think we could get away with regular markers that don't have an `update` method, and that would simplify the code quite a bit.

**Comment by brismuth** [comment]
K. I haven't looked into it a whole lot, but that implementation sounds good to me. I'll look into doing it that way.

**Comment by brismuth** [comment]
So I spent quite a bit of time fooling around with using Ace's markers, and couldn't really get it working at all the way we'd want. Then I realized an alternative, significantly easier option. Basically, while searching through the lines, when I find a match, I add a mapping to the tab object, between the search results tab row number and the file we'd want it to open (and row we'd want to jump to). Then we capture click events on the editor, and we only do anything with the event if the tab object has the mapping. Then we open the file and jump to the line, if the mapping contains the clicked line. I made the tabs read-onlyable to prevent the mappings from getting messed up.

It sounds a little hacky, but actually works really well, preserving links across multiple searches etc.

**Comment by thomaswilburn** [comment]
Closed via 2418b6f049e1b3f93c37ef5641db4f5e19f4e470 and a5557f5fd48ca19c4e7b63e30c4c608e7e625f48 (and #462, of course)

**Comment by brismuth** [comment]
The change looks good! Definitely prefer the functionality/look of the markers, although I think double click may be a better choice to bind to; that's what sublimes does. The benefit would be that you could highlight text or copy it without the event firing. Not a big deal either way though. 

I agree with taking out the close button, mostly. I included it originally because right now there is not a way to minimize the search bar if you're not currently clicked inside the search input, which isn't very intuitive. Sublime lets you close it by hitting `esc` no matter where your focus is. Not sure if you'd want a global listener like that though, so I added the `x` button.

Also, on a side note, part of this issue was to add highlighting, meaning an Ace syntax highlighter override, like this: 

![image](https://cloud.githubusercontent.com/assets/5679695/10826017/4b020aca-7e2d-11e5-9ff8-d54bf543d48f.png)

I can add a separate issue for the syntax highlighting if you want.

**Comment by thomaswilburn** [comment]
Double click was one of the original plans, but unfortunately Ace doesn't hand us the row for that event the way they do for single click. I'm not sure why. So I went with the lazy option, rather than trying to add the code to determine the row from the screen coordinates.

I think it would be nice to have syntax highlighting -- one of the few cases where I'm happy to deviate from Ace upstream. Definitely open a new issue for that.

**Comment by brismuth** [comment]
Instead of determining the row from the event or screen coordinates, you can also get the row from `editor.getCursorPosition().row;` the way I did in #462. 

I'll open a separate issue for the ace highlighting.

**Comment by thomaswilburn** [comment]
Good to know! I missed that part when I was looking through your code to implement this.
