### ISSUE TITLE
problem with rebinding the keys

### ISSUE THREAD

**Issue by rumatakira** [thomaswilburn/Caret#485]
I have changed Ctrl-D to Ctrl-K and redefine Ctrl-D, but the last doesn't work:
"Ctrl-K": "sublime:select-or-more-after",
"Ctrl-D": { "ace": "removelines" },

**Comment by thomaswilburn** [comment]
This is not a bug. "removelines" is not a valid Ace command, at least in the version that we ship. "removeline" is, and if I set that to Ctrl-D, it seems to work just fine. Is there something I'm missing?

**Comment by rumatakira** [comment]
Yes it works. Thank you. In current Ace documentation there is no such command "removeline" but "removelines" https://ace.c9.io/#nav=api&api=editor . So notice that if you'll change the Ace vertion. ;)

**Comment by thomaswilburn** [comment]
Honestly, the Ace documentation is kind of a garbage fire, but in this case they're talking about different things. There's `removeLines()` which is a method of the editor, and `removeline` which is a command available through the `editor.execCommand()` method. Since the latter is the way we actually communicate with Ace in our keyboard bindings, I suspect it's pretty stable.

**Comment by rumatakira** [comment]
Thomas, by the way - one more question. Not to open a new topic. Is it possible to change the type of highlighting paired brackets? In the theme of cobalt - it almost can not be seen.

**Comment by thomaswilburn** [comment]
Not without altering the visual theme, no.

**Comment by rumatakira** [comment]
Ok. Thank you one more.
