### ISSUE TITLE
associating with mime type "application/*" can be a bad thing

### ISSUE THREAD

**Issue by vapier** [thomaswilburn/Caret#500]
the manifest.json file registers itself like so:

```
  "file_handlers": {
    "text": {
      "types": [
        ...
        "application/*",
```

this ends up catching all sorts of binary files, including many compressed types (like 7z or tar.gz archives) which often times are very large files.  i understand you're trying to make it easier to open up unknown file types, but this seems to be more of a bad idea than good.

for example, if someone installs a file handler for archives (like this [archiver program](https://chrome.google.com/webstore/detail/mljpablpddhocfbnokacjggdbmafjnon)), Caret still ends up being the default until people manually adjust it (and have to do so for multiple file types).

can you just locate some of the more common/popular mime-types and list those explicitly ?  if someone really really wants to open a random file, they still can through Caret itself.

**Comment by thomaswilburn** [comment]
See also: #492, #493.

Personally, I think this is a bug in Chrome: if the user already has a file association assigned, as with an archiver, why is it letting Caret take that over?

That said, I'm happy to implement a change to address this, I just haven't had time to experiment to figure out what will give us good-enough type coverage without excluding a bunch of fairly typical things (and thus triggering a new wave of "Caret no longer opens my source code" bugs). Since none of this is well-documented, there's no way for me to know what MIME types are going to do the trick.

If you wanted to help out, it would be great for someone to clone the Rosetta Code repo and figure out what registration strings get us to coverage for most of the programming languages in there. The weirdos can always fend for themselves, but I'd like to have at least the top 50 handled out of the box.

**Comment by vapier** [comment]
i don't think ordering would really solve this problem.  if i installed Caret first, and then WGU, why would Chrome know that WGU is a "better" default option ?  because Caret is using a glob ?  what if the app was an XML viewer and used "application/xml" ?  how would Chrome know which is better ?

if i'm tracing the Chrome code correctly, it doesn't actually have a full mime db.  so using something like `application/*` wouldn't mean you'd actually match the [full IANA db](https://www.iana.org/assignments/media-types/media-types.xhtml), just whatever Chrome itself supports.

* [chrome/browser/extensions/api/file_handlers/mime_util.cc](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/extensions/api/file_handlers/mime_util.cc) calls `net::SniffMimeType` and `net::GetMimeTypeFromFile`
* [net/base/mime_sniffer.cc](https://code.google.com/p/chromium/codesearch#chromium/src/net/base/mime_sniffer.cc) handles a few common mime types and returns a small list (MS Office, HTML, XML, CRX, etc...) before falling back to a reduced magic number list (look at `kMagicNumbers` and `kExtraMagicNumbers`)
* [net/base/mime_util.cc](https://code.google.com/p/chromium/codesearch#chromium/src/net/base/mime_util.cc) has a reduced list of mime types -- see `kPrimaryMappings` and `kSecondaryMappings`.

so if you used that list alone to figure out which mime types you want to handle, i think that'd be about the best you could do mime-wise.  it would probably also help to list some common file extensions (independent of mime type) so you wouldn't break the common case.  e.g. make sure the manifest says you can handle `.txt`, `.log`, `.xml`, `.c`, `.cxx`, etc... regardless of mime.

**Comment by thomaswilburn** [comment]
Yeah, that's what I had gathered from looking at the Chrome code myself. It's not terribly comprehensive.

I actually do think that Chrome should handle this in terms of specificity instead of installation order. `application/*` should always come after someone who declares a specific MIME type, like `application/xml`. But installation order also makes sense to me because it provides the least surprise to users--if Caret is already associated with files, installing an archiver won't surprise you if you have to set it as the default. But when you have an archiver installed and then Caret takes over that extension, it's a bad experience, and I get blamed for it even though I don't really think it's my fault.

I'm happy to take a pull request for this if you want it fast. I was planning on rolling out a maintenance release this week anyway. Otherwise, you'll have to wait for me to get some free time and run through all the 250+ extensions that Caret supports and see which ones I want to manually manage, and how much grief I'm ready to get from the community on it.

I'd also be happy to go back to automatically adding extensions to the manifest via a Grunt task if you can talk the Chrome team into raising the per-app registration limit. Then we don't have this issue at all.
