### ISSUE TITLE
Shutdown Garbles Code

### ISSUE THREAD

**Issue by mattlockyer** [thomaswilburn/Caret#514]
Hi, first of all great work been using for years yada yada, you rock!

I have had this happen a few times:

When I shutdown without closing files, or the editor (files are saved). The next time I start up my code is garbled. It happens with JS and HTML but not CSS... curious why / can this be resolved please?

I use a Pixel Gen1 and Lenovo N21.

Otherwise I LOVE CARET! Thanks!

**Comment by thomaswilburn** [comment]
I've seen this happen several times in the past. I'm not sure why it happens, but I believe it's at a layer farther down than Caret is--I believe the Chrome runtime is not correctly writing to the open file handles. The best advice I can give you is to work with code in a version-controlled setting, such as a Git repo, that isn't controlled by Caret, so that you will always have backups available. Also be sure to close Caret before shutting down, just in case. I'm sorry, I wish I had a better answer for you.
