### ISSUE TITLE
Alt+Q does not work with double-byte Chinese character

### ISSUE THREAD

**Issue by xdrwedc** [thomaswilburn/Caret#515]
### Type of issue (choose one):
  - [ ] Bug

### Test steps
Alt+Q does not work with double-byte Chinese character

Step 1 Before Alt+Q http://prnt.sc/b37fh6
Step 2 After Alt+Q http://prnt.sc/b37hv1

[Before.Alt.Q.txt](https://github.com/thomaswilburn/Caret/files/261626/Before.Alt.Q.txt)
[After.Alt.Q.txt](https://github.com/thomaswilburn/Caret/files/261627/After.Alt.Q.txt)

![before alt q caret b37fh6](https://cloud.githubusercontent.com/assets/18275747/15219891/0fde9ccc-182b-11e6-9c20-b456e2423aab.png)
![after alt q caret b37hv1](https://cloud.githubusercontent.com/assets/18275747/15219890/0fdc8504-182b-11e6-906a-53fc46c0abb6.png)

### Description

Could you consider making Alt+Q wrap double-byte Chinese characters to the margin line. Since one Chinese character is encoded in two bytes, so one Chinese character should count 2 in "wrapLimit" in User Preferences.

Example #1 

Let's set "wrapLimit" to 78 in User Preferences.

We type 60 English characters and 10 Chinese characters (count 20 bytes) in a single line.

If we use Alt+Q, the line should be wrap at the ninth Chinese character. i.e. sixty English characters count 60 bytes + nine Chinese characters count 18 bytes, 78 bytes in total.  

Thanks Thomas 汤姆

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
This is a great bug, but I may be over my head. I'll see what I can do. I think it may be a simple fix, but I didn't write the original wrap code, and internationalization isn't my strong suit.

**Comment by xdrwedc** [comment]
Thomas, I see your Chinese name 汤姆 on your personal site thomaswilburn.net. Chinese/Japanese/Korean are all double-byte characters (DBCS). 

Since over 800 million internet users use double-byte character set and Caret app is the greatest text editor for Chrome OS, if we can make it work with DBCS, it will be a significant impact. 

Would you please help report this bug to Ace editing component development team?

I'm a salesman, not really familiar with communication with coding engineer. During the process of bug report to Ace, I can do as you say, like providing more bug examples and etc.

**Comment by thomaswilburn** [comment]
Yes, I studied Chinese for a couple of years in college. But it's been a long time, and I never had to deal much with Chinese text files during that time (plus, I was never fluent). So my apologies for any clumsiness you might encounter.

After looking at the code and your examples (seriously, great job reporting this bug, lots to work with here), I think the problem may be a misunderstanding with how Caret is displaying and counting your characters.

Caret is written in JavaScript, and internally JavaScript uses the two-byte UTF-16 or UCS-2 for _all_ text strings, English or otherwise. So when we wrap, we are working through the characters of the string, not the bytes that make it up. That's a good thing: you probably wouldn't be happy if Caret put an ASCII new line character between two of the bytes that make up a Chinese character, because it would change the characters themselves!

I think the problem is that it doesn't _look_ right, and the reason for that is that although both your English and your Chinese characters are monospace, they're monospace with different display widths per character. In other words, the fact that the byte-length is double, and the character width is double, is just a coincidence. If you use Alt-Q to wrap a line, and then select the resulting lines, they are the correct character length, but visually they're obviously not correct.

I think the Ace bug you would want to contribute to and/or watch is [this one](https://github.com/ajaxorg/ace/issues/460), which says that it's for "varying character widths" but specifically calls out internationalized text as one of the issues it fixes. I'm not sure what the ETA is, since that bug was opened in 2012. I suspect it needs an owner, or someone to help sponsor it through. If you're not a technical person, you may need to get in touch with someone who is, or one of the people in that thread who are offering pull requests and see if they're willing to push it with Ace again.
