### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by richiksc** [thomaswilburn/Caret#521]
### Type of issue (choose one):
- [ ] Bug
- [x] Feature request
- [ ] Question

We could probably do trapezoidal tabs and real icons for the window controls instead of **[ - | + | ~ ]**.

I've created a CodePen [here](http://codepen.io/richiksc/pen/KMMBzK) for trapezoidal tabs in CSS.

**Comment by thomaswilburn** [comment]
I'm attached to the window controls, personally. 

Are trapezoidal tabs a big improvement? I was going for Material-ish design, and the tabs in something like Polymer are just rectangles.

**Comment by NoahVlncrt** [comment]
I have to agree with @richiksc I very much enjoy those tabs better

**Comment by brismuth** [comment]
Just throwing in my 2 cents, I prefer the rectangle tabs as well.

**Comment by brismuth** [comment]
And while the default skin for Sublime has trapezoidal tabs, a lot of people prefer to use the [Afterglow theme](https://github.com/YabataDesign/afterglow-theme). Or at least, I like to, and it has a lot of stars. :)

**Comment by richiksc** [comment]
Sure, but the tabs in Caret just look a bit outdated. Maybe the active tab indicator could be a little less thick, and i think a little bit more padding would help if you want Material-ish.

@thomaswilburn Why are you so attached to the window controls? The tilde doesn't even look like something that could mean "close".

Sorry if I sound really critical about the window controls, I always try to think of things from the perspective of a basic user, even though most coders (the target market for this app) aren't that basic. It just improves usability and UX.

**Comment by thomaswilburn** [comment]
I like the window controls just because Caret has always had weird window controls and they've grown on me. There was a PR a while back to swap them with something more standard, but it just felt wrong to me when I tried it out, and after some (positive) discussion I didn't end up accepting. I'm not philosophically opposed to changing, I just kind of feel like they're part of the app's personality now, like those horrible square menus that WinAmp used to have.

I'll happily take a look at pull requests to make the tabs (or any part of the UX) better. I'm not a designer, so Caret has basically just crawled forward by revising the ugliest portions one step at a time.

Please remember that the tabs exist in several states (saved, unsaved, active, inactive, dragging, dropped) that all need to have functional styles, and that you'll need to test the JS thoroughly before altering their internal DOM structure. CodePen isn't very helpful to me, because it doesn't show whether or not the functionality is still preserved after the cosmetic changes.

**Comment by richiksc** [comment]
The CodePen is just a way to show how trapezoidal tabs are possible with just CSS using 3D transforms.  As far as the window controls go, I'm relatively new to Caret, so they haven't really grown on me. 

If you are very attached to them (and probably many early adopters of Caret), there are always options. You could have a preferences option for the window controls, with the default as the standard-style window controls, so new users can understand the UI. Advanced users of Caret (most early adopters) can change it to the 'unique' window controls.

**Comment by YemSalat** [comment]
I made some tweaks to my own version of caret (making it resemble my Sublime setup)

Agree with OP that the tab border could be thinner (I think too distracting with current dark theme and bright orange accent color), also the dark theme could be a bit darker in my opinion.
And maybe loose the shadow on the sidebar.

Here is whjat mine looks like now:
![screen shot 2016-07-26 at 4 39 39 pm](https://cloud.githubusercontent.com/assets/2361381/17128480/5488a47a-5350-11e6-81f0-5cd02b594d26.png)
_(click to zoom)_

PS I am a new Caret user and I do like the window controls, I think they add uniqueness, they grown on me from the first sight :)
