### ISSUE TITLE
The future of Caret?

### ISSUE THREAD

**Issue by fghhfg** [thomaswilburn/Caret#534]
Chrome package app is doomed.

What would you do?

ref: [From Chrome Apps to the Web](http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html?m=1)

> We will be removing support for packaged and hosted apps from Chrome on Windows, Mac, and Linux over the next two years.

**Comment by thomaswilburn** [comment]
It's not doomed on Chrome OS, which is why I wrote it in the first place. Users on other platforms have a fine choice of free editors they can use. I'm also going to try to work more with standards organizations to fill in the APIs that Caret would need to run in a browser. Development will continue, albeit slowly.
