### ISSUE TITLE
Auto-save.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [thomaswilburn/Caret#535]
I just lost all my work. I don't like saving files on my computer so everybody else can look into them.

**Comment by AnastasiaDunbar** [comment]
It happened when WebGL crashed on chrome, the screen went black and every application crashed.
Once when I quickly accidentally closed and opened the lid, it restarted. But it's the Chromebook's operating system itself.
There are many reasons that Chromebook can crash, that's why an auto-save could help. I mean the settings are saved, why can't the files be saved?

**Comment by thomaswilburn** [comment]
Caret already has an auto save function, look in the user prefs to enable it. 

I don't entirely understand how your comments relate to each other, do you want it to save files or not? While there is a bug for Caret to back up unsaved files to non-volatile storage, there's no ETA for when I'll get to that, because it has a lot of tricky implications.

**Comment by AnastasiaDunbar** [comment]
Thanks. I thought it should've auto-save by default.
