### ISSUE TITLE
Dropbox synchronization

### ISSUE THREAD

**Issue by AnastasiaDunbar** [thomaswilburn/Caret#536]
While the file was being saved my screen turned black and Chromebook restarted by crash. 
My text is corrupted, unreadable and it's unrecoverable. Syncing to Dropbox would've been great.
![2016913](https://cloud.githubusercontent.com/assets/11806048/18491660/b0b53384-7a07-11e6-9039-6675eb490b69.png)

**Comment by thomaswilburn** [comment]
Caret will not add built-in support for anything other than raw files, sorry. I feel your pain--it's happened to me too. If Dropbox were to build a file system extension for Chrome OS, we could use that, because it would present to us as a regular folder, but that's it.

Another alternative is to keep files that you're worried about in a Git repo, which should be recoverable even after a crash.

Updating to use a remote filesystem would, among other things, require me to update my privacy policy and agree to Dropbox's API. And writing sync code isn't my forte. So Caret just edits files, and leaves the rest of it to the service to implement through the available OS hooks.

**Comment by richiksc** [comment]
There is an extension on the Chrome Web store called Dropbox File System
for ChromeOS.

**Comment by brismuth** [comment]
It should be noted that the extension is unofficial. Basically, you would install and configure the dropbox extension first. Then Caret would see it as a local folder, and the dropbox extension would handle all the syncing.
