### ISSUE TITLE
Intellisene / project code analysis feature?

### ISSUE THREAD

**Issue by pwFoo** [thomaswilburn/Caret#544]
I found Caret during my Atom had some problems and tested it. It's really nice!

Is a intellisense / project code analysis feature planned?

**Comment by thomaswilburn** [comment]
No, we don't plan to add that on our own. If Ace implemented it, we might as well, but Caret's focus is on being small and fast. You may want to check out Visual Studio Code instead.

**Comment by pwFoo** [comment]
Sure Visual Studio Code has implemented it? Tested Visual Studio Code, Netbeans, Atom and some more editors / IDEs without success.

Also tested [Neutron Drive](https://super.neutrondrive.com/), (Cloud9)[https://c9.io/], (Orion)[https://orionhub.org/mixloginstatic/landing.html?redirect=https%3A%2F%2Forionhub.org%2F&key=FORMOAuthUser] and some more, but Caret is fast, feature rich and feels like the better solution.

Caret would just need some helpful plugins in the future. 
Would also be nice to see it stand alone and browser based, but i read it somewhere that this isn't planned.

So thank's for your great work! Caret is ready to be used for every day work!

**Comment by thomaswilburn** [comment]
I may be misunderstanding what you mean by Intellisense, but VSCode is as close as I'm aware to what you want, within the capabilities of the language.

If you wanted to run Caret standalone, my understanding is that NW.js implements the necessary `chrome.*` APIs to do it.

**Comment by pwFoo** [comment]
The IDE should read the project classes and methods from all the files inside the project directory. Some editors get it done by a "stubs.php" file (Netbeans, but I can't get it work). I don't know what the correct name is.
Static code analysis I think?

So with a NW.js Chrome isn't required to run Caret? Could be a nice way to use a lightweight and great IDE without dependencies. :)
For example it could be used stand alone with any browser like cloud9 or orion optional running inside a docker container.

I moved from Netbeans to Atom (nice UI, plugins, git integration, [ungit plugin](https://atom.io/packages/atom-ungit), ...), but anymore without the feature I tried to explain.
I tested VSC and some more, but stay with Atom. But sometime it's really slow...

Because git could be used from OS / ungit @ browser it looks like Caret have all the base features I use (multiple select, ui, workflow) with a nice and handy UI (which makes it better than Neutron Drive for me). 👍

**Comment by thomaswilburn** [comment]
Not exactly, NW.js would create a standalone instance of Caret that doesn't require Chrome (because it would effectively bundle its own copy of Chrome with the app), but that won't make it work in any browser. Caret requires API support for things like file writing and storage, and browsers do not provide these to normal non-extension pages, and probably never will. 

Caret probably isn't a very good fit for Docker containers, since it depends on a lot of system infrastructure (including the GUI) and doesn't have any network file support. You'd be better off exposing a network file system and using any editor you want.

I'm glad you're enjoying it, though! Please feel free to file pull requests if you add any useful features.
