### ISSUE TITLE
Keep the Esc key from exiting fullscreen mode

### ISSUE THREAD

**Issue by plurry** [thomaswilburn/Caret#546]
How do I keep `Esc` from exiting immersive fullscreen? This is especially annoying because it does it even when there's a dialog box open or I have multiple cursors I want get rid of.

I'm on Chrome OS 54.0.2840.101.

**Comment by thomaswilburn** [comment]
Good question: I'll look into it, there may be a way for us to add a null keybinding and prevent it.

**Comment by thomaswilburn** [comment]
This doesn't appear to be possible. I suspect it's for security reasons--in a browser, you can't override the Esc key in fullscreen to prevent phishing attacks. You could argue that packaged apps shouldn't face the same requirements (and I would probably agree) but the point is moot, since the Chrome team has effectively deprecated packaged apps as of this year.

**Comment by plurry** [comment]
If you add `app.window.fullscreen.overrideEsc` to the permissions in the manifest then `preventDefault` works. See https://developer.chrome.com/apps/app_window#type-AppWindow.

**Comment by thomaswilburn** [comment]
Ah, interesting. Thanks! I'll work that into the next release.
