### ISSUE TITLE
Miscellaneous issues

### ISSUE THREAD

**Issue by plurry** [thomaswilburn/Caret#547]
Hi, thanks for Caret. I've used it for a couple days and I love it 95% of the time. For that last 5%, I've written down the issues I've had and I'm hoping someone can help me resolve them.

I want to:
* have `Ctrl+Left`, `Right`, `Backspace`, and `Delete` treat the whitespace between the cursor and the word as part of the word 
* keep undo and redo from selecting the text that changed
* have `Ctrl+Tab` and `Ctrl+Shift+Tab` go forward and backward in the order that the tabs are arranged

Some less important things to make Caret more like Sublime, I'd like to:
* disable the save dialog if the tab is empty and hasn't been saved before
* see the space and tab characters in text I've selected
* have `Ctrl+P` list open tabs so I can scroll through them
* have `Ctrl+F` reopen the find dialog if it's already open instead of opening the replace dialog
* have `Ctrl+Shift+T` reopen the last closed file

Some random other nice-to-haves, I'd like to:
* be able to use three-finger swipes to switch tabs
* be able to hover over the OS shelf in fullscreen to make it appear
* have a gap between the tab handles in fullscreen so I can tell tabs apart more easily
* open multiple Caret windows
* open Caret tabs in a Chrome window

Thanks for any help :)

**Comment by thomaswilburn** [comment]
I'm not actively developing Caret at the moment, so while this is a reasonable list, I wouldn't expect it to happen anytime soon. Also, in the future, please file individual issues--it's not realistic to file an issue for "stuff Plurry wants" and then track it in a comparable way to the other issues here.

Some of these things do exist. Sequential Ctrl-Tab is available as the `session:change-tab-linear` command, and you can just rebind them in your keyboard shortcuts.

Some of them, such as the way that the editor treats whitespace, will require edits to Ace. Caret does not, as a general rule, monkeypatch Ace, so you'd want to file those as issues against them.

Swipe gestures, multiple windows, and opening Caret in a browser tab are not possible due to the architectural and platform reasons. You may want to search the issues database to see whether we've addressed other problems--I probably have, over the last four years, and you can probably find out why.

Finally, although this stuff just can't be a priority for me right now, I do happily accept pull requests, and in fact the last two or three minor revisions to Caret have been driven by patches sent in from the open source community, which is really great.

**Comment by thomaswilburn** [comment]
I'm not actively developing Caret at the moment, so while this is a reasonable list, I wouldn't expect it to happen anytime soon. Also, in the future, please file individual issues--it's not realistic to file an issue for "stuff Plurry wants" and then track it in a comparable way to the other issues here.

Some of these things do exist. Sequential Ctrl-Tab is available as the `session:change-tab-linear` command, and you can just rebind them in your keyboard shortcuts.

Some of them, such as the way that the editor treats whitespace, will require edits to Ace. Caret does not, as a general rule, monkeypatch Ace, so you'd want to file those as issues against them.

Swipe gestures, multiple windows, and opening Caret in a browser tab are not possible due to the architectural and platform reasons. You may want to search the issues database to see whether we've addressed other problems--I probably have, over the last four years, and you can probably find out why.

Finally, although this stuff just can't be a priority for me right now, I do happily accept pull requests, and in fact the last two or three minor revisions to Caret have been driven by patches sent in from the open source community, which is really great.

**Comment by plurry** [comment]
I've moved on from Chome OS for now, but if someone else is interested...

You can enable `session.$selectLongWords` to fix the whitespace behavior without touching Ace internals.

To fix undo you do have to edit Ace to call `UndoManager.undo()` and `redo()` with `false` instead of `true` in a couple places but it's simple to do.

I didn't get any farther than that before I quit messing with it, but that along with `session:change-tab-linear` did take care of my main complaints.
