### ISSUE TITLE
Ace features missing?

### ISSUE THREAD

**Issue by lw1990** [thomaswilburn/Caret#550]
Using the kitchen sink at https://ace.c9.io/build/kitchen-sink.html, if I type `if {` in the autohotkey language, then press enter, it automatically indents and closes with a `}` on a newline
this doesn't seem to happen in Caret, is there a way to enable it?

Also, in the AHK language, if I type `"` in the kitchen sink, it automatically closes it with another `"` and puts the caret in between. This only seems to happen in Caret for certain files (like js files), is there a way to make it happen for .ahk files?

Finally, in the ace kitchen sink, checking the option "Show token info" is very helpful to me and shows tooltips on the different types of tokens, is this possible to enable in Caret?

**Comment by thomaswilburn** [comment]
I don't know what plugins are loaded in the Kitchen Sink (it's probably everything). We only load a subset of plugins for Caret, but if you run from source, you can enable any features you want. That goes for Show Token Info as well.

It's not clear to me why the behaviors (Ace's term for automatic quote/tag insertion) isn't working for AHK, since they're enabled everywhere else by default. I'd be happy to take a pull request if it turns out that there's a simple fix for it.
