### ISSUE TITLE
1px white column on the right

### ISSUE THREAD

**Issue by serna08** [thomaswilburn/Caret#589]
### Type of issue (choose one):
  - [x ] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps
-open Caret on chromeOS
-there is a white column to the right of width 1 px

### Description
Upon opening Caret in either maximized window or fullscreen, a 1px wide white column appears to the right of the screen.

### Additional notes
none

### System details
-ChromeOS Version 60.0.3112.112 (Official Build) (64-bit)
-Acer R11

##edit1: deleted template text

**Comment by thomaswilburn** [comment]
This is a known issue, which you can see defined here: https://github.com/thomaswilburn/Caret/blob/d5602d5353c01632e89e11445f8961060f96de20/css/base.less#L28

This line exists so that the light/dark themes have something to create a little contrast, particularly on operating systems like Windows 10, which has a lot of white space. We could possible show and hide it using a class in the main.js file, as we do for the immersive mode. I'll see what I can do, but you're also welcome to file a pull request if I don't get to it right away.

**Comment by serna08** [comment]
Ok thank you!
