### ISSUE TITLE
Add option to disable "Caret has updated" notification

### ISSUE THREAD

**Issue by Simon-Tang** [thomaswilburn/Caret#601]
### Type of issue (choose one):
  - [ ] Bug
  - [X] Feature request
  - [ ] Question

### Test steps

1. Thomas releases a Caret update

### Description

I think the average user would prefer not to have the notification until they open Caret.

**Comment by thomaswilburn** [comment]
We handle these things from the background page, and it's kind of a pain in the ass to get settings from there. I'd be happy to take a pull request for this, but otherwise am inclined to leave the behavior as-is. Normally I don't release updates as often as I have done this week, so it's not as much of an issue.

**Comment by Simon-Tang** [comment]
I'll give it a go - I'm thinking of a "notifyOnUpdates" setting that's one of "realtime", "startup" and "silent". 

The only thing I'm a little unsure of is where to store a boolean on whether or not there's a pending upgrade notification. Settings singleton or elsewhere? Needs to be persistent across device reboots. Thanks :)

**Comment by thomaswilburn** [comment]
The Chrome local storage is literally made for this. But you'll need to extract the setting during a reset command and transfer it over to the raw chrome.storage.local object so the background page can access it (from installer.js).
