### ISSUE TITLE
Python indentation size

### ISSUE THREAD

**Issue by andwilley** [thomaswilburn/Caret#603]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

It seems like in one of the recent releases the default indentation width is ignored for python files. I was wondering, since all the new tabs I will be able to make will be 4 spaces wide, if Caret could convert the existing tab characters in my file when it opens them to 4-space-wide tabs, instead of 2 individual space characters? 

In previous versions of Caret I wrote these files with the default indentation set to 2. Now my new tabs span 4 spaces and the rest of the tabs that already exist in the file have been converted to 2 space characters. It is easy for me to find and replace these, but it would be nice not to have to. It doesn't seem to anger the python interpreter and gedit still sees all these characters as tabs, so it must just be an issue with the editor displaying them.

I really like this program, so thanks for all the work.

### System details

Chromium Version 61.0.3163.79, running on Ubuntu 14.04 (32-bit)

**Comment by thomaswilburn** [comment]
A recent release turned on syntax-specific indentation settings, configured in the user preferences. If you view the default user prefs, you'll see where the Python settings are being merged in. Four-space indentation for Python was a common request, since it's the standard according to PEP8. You can disable syntax-specific settings by adding `syntaxSpecific: {}` to your user preferences if it's not already there.

As a side note, all indentation by default is in spaces, the editor just treats them as tabs. If you turn on visible whitespace, you'll see that this is the case. So it's not that your previous files were converted from tab characters to two-space indentation, it's that they were always two-space indentation and the editor just doesn't recognize them as indentation levels once the setting changed.

**Comment by andwilley** [comment]
Thanks. MIssed that in the default user prefs. My bad. Thanks for the quick reply.
