### ISSUE TITLE
Add support for CSS variables

### ISSUE THREAD

**Issue by rossjrw** [thomaswilburn/Caret#659]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

![screenshot 2018-11-13 at 22 40 35](https://user-images.githubusercontent.com/29130152/48447915-49da8080-e795-11e8-9385-7969cd8044ab.png)

### Description

I'd like to request adding support for variables in CSS.

**Comment by thomaswilburn** [comment]
Hopefully it's in Ace, if so I can roll it right in.

-----Original Message-----

**Comment by thomaswilburn** [comment]
So unfortunately, the CSS mode in Ace doesn't seem to get a lot of love, and the newest version doesn't support CSS custom properties (or even `var(...)` or `calc(...)` expressions in a lot of places where they should be supported). You may have better luck with your highlighting if you set the syntax to run as LESS instead--since that language is a superset of CSS, it would highlight correctly at least, even if the linting might end up less strict than you'd like.
