### ISSUE TITLE
Caret not default, and not show in 'open with' (yaml)

### ISSUE THREAD

**Issue by Justin-Maxwell** [thomaswilburn/Caret#668]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Test steps

From Chrome-OS Files, right click a .yaml file, Caret not listed as option.

### Description

I would like to be able to open .yaml files directly from Files into Caret, but the association doesn't seem to be there, and I can see how to add one?

Currently, for me, .yaml files were opening (only) in '<txt> Text'.  I just uninstalled that and now can't open them at all from Files. 

*Version 70.0.3538.110 (Official Build) (64-bit)*

**Comment by thomaswilburn** [comment]
We currently match against Files using a wildcard for application files in our manifest, since we hit the limit for how many extensions we were allowed to declare fairly early. I think this is probably a bug that should be filed against Chrome, so that it can categorize .yaml correctly by MIME type.

**Comment by Justin-Maxwell** [comment]
I don't know what changed - but either the Chrome 71 update or the recent Caret update seems to have fixed this for me.
