### ISSUE TITLE
Text selection bug on window focus after a file save.

### ISSUE THREAD

**Issue by blakjakau** [thomaswilburn/Caret#722]
### Type of issue (choose one):
  - [ X ] Bug

### Test steps
Only tested this on Chrome OS
- Save a file in Caret
- move focus to another window
- return to Caret

### Description

Upon returning to Caret after a file save operation: 

the editor automatically selected all text
OR 
(sometimes) all text up to the cursor click location
OR
(Rarely and I can't reproduce this - If clicking into another tab) 
replaces the entire buffer with the content of the just saved file

### Additional notes
If I re-focus the window without clicking into the text (i.e. click the title bar) the "select all" version of bug will fire every time.

### System details

Chrome OS Version 80.0.3987.128 (Official Build) (64-bit)
Not using Beta or Dev channels.

**Comment by agarian-2** [comment]
I have this happen too, and it can get very annoying when I want to Ctrl+F, not expecting the entire file to select. Another rather annoying thing that sometimes happens when unfocusing from the window is when a file is not saved, and I focus into Caret again, it says the file was changed and asks if I want to reload or not. I use Windows 10 and the latest Chrome version.

And sorry for probably making you think I'm a contributor in notifications, but I'm just here to clarify that this isn't an isolated issue.

**Comment by westwallpoma** [comment]
+1 for this ; I've experienced consistently for well over a year now.  Perhaps longer.  Can be bothersome if I'm not prepared for it as, after highlighting all the text, it'll replace the entire contents with whatever I type.

Which is fine, because I can CTRL-Z to revert, but it can be pretty annoying.

**Comment by thomaswilburn** [comment]
This often happens due to the way that files are loaded asynchronously over a sluggish filesystem. You may want to set the "disableReload" option to see if that fixes the issue.

**Comment by westwallpoma** [comment]
Thanks @thomaswilburn ; this appears obvious now in the context of the ``user.json`` file. :)

```
  //If the editor jumps to the top on focus change, set this:
  "disableReload": true,
```

Thank you very much for Caret - great piece of software.

**Comment by agarian-2** [comment]
That seems to have fixed my problem, thank you!

**Comment by blakjakau** [comment]
just FYI, this setting also fixes for me.
