### ISSUE TITLE
[Feature request] Live preview for some languages

### ISSUE THREAD

**Issue by Explosion-Scratch** [thomaswilburn/Caret#754]
I think that it would be really nice to have a live preview of code. Most other online editors have this, and I see no reason why Caret shoudn't. My request is for previewing of HTML, CSS and JavaScript. JavaScript preview could be as simple as showing a console and an encouragement message to include it in a HTML file to see the results (It's use a blank HTML file to support DOM manipulations), and for HTML that's really simple, just show the page, and CSS should have no live preview unless linked in an HTML file. 

I have no knowledge of other programming languages, so depending on how hard this would be it'd be nice to add a compiler to run C, C++, C#, Python, Ruby, some of the others too, but I imagine that'd be beyond the scope of this project, and too hard to add. Still a basic HTML preview shouldn't be too hard! (just write to an iframe)

### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Test steps

_N/A_

### Description

It'd be nice to have a live preview of HTML code and limited support for live preview of only JS code. JS and CSS could then be linked in the HTML and previewed.

### Additional notes

Writing to an iframe to get the preview would be easy to do, it also allows sandboxing to prevent altering the parent window.

### System details
_No_

**Comment by thomaswilburn** [comment]
Currently Caret has no network permissions, which makes our privacy policy simple and keeps the software secure. I'm not particularly interested in changing that, and we'd need to in order to add an HTML preview. We'd also need to rewrite big chunks of the layout code and figure out how to manage live reload for arbitrary content without crashing our own process or opening up a hole in our own sandboxing.

It's not quite as easy as it seems, basically, and since Caret is largely in maintenance mode while we wait for Google to eventually kill off packaged apps completely, I think we'll have to skip this feature.

**Comment by Explosion-Scratch** [comment]
> It's not quite as easy as it seems, basically, and since Caret is largely in maintenance mode while we wait for Google to eventually kill off packaged apps completely, I think we'll have to skip this feature.

I think that this is a big enough feature that most other editors have. This is the main reason that I use online editors such as [Codesandbox](https://codesandbox.io), [repl.it](https://repl.it), and [codepen](https://cdpn.io). I like what you guys are doing here but I think that your user count would increase by 5x if you added this. I'm sure that users wouldn't mind an extra permission prompt, right? Especially if this was optional. And what if it just auto-saved a temporary file in a folder and opened it in chrome with auto-reload? That might be another easy approach, right?

**Comment by thomaswilburn** [comment]
I don't care about user counts, the permission can't be optional since it has to be in our manifest, and for a lot of the places Caret is deployed (such as schools) its offline nature is genuinely important. 

If you're going to run the preview in a Chrome tab anyway, why not just combine Caret with real dev tooling that does what you want and is language specific? This is an editor, not an IDE, and we stick to the UNIX ideal of doing one thing well. If you want those other features, it's okay to use something else.

**Comment by Explosion-Scratch** [comment]
ok
